### ISSUE TITLE
Uncaught InvalidStateError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The imag...

### ISSUE THREAD

**Issue by ghost** [atom-ide-community/minimap-plus#15]
1. Launch Atom
2. Have file tree or similar open
3. Resize Atom window such that there is no room for the minimap to render.

**Atom**: 1.53.0-nightly17 x64
**Electron**: 6.1.12
**OS**: Mac OS X 10.15.7
**Thrown From**: [minimap-plus](https://github.com/atom-ide-community/minimap-plus) package 4.32.0

### Stack Trace

Uncaught InvalidStateError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.

```
At /Users/boptilop/.atom/packages/minimap-plus/lib/canvas-layer.js:64

Error: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at CanvasLayer.copyToOffscreen (/packages/minimap-plus/lib/canvas-layer.js:64:27)
    at HTMLElement.redrawRangesOnLayer (/packages/minimap-plus/lib/mixins/canvas-drawer.js:300:11)
    at HTMLElement.updateTokensLayer (/packages/minimap-plus/lib/mixins/canvas-drawer.js:145:10)
    at HTMLElement.updateCanvas (/packages/minimap-plus/lib/mixins/canvas-drawer.js:109:10)
    at HTMLElement.update (/packages/minimap-plus/lib/minimap-element.js:892:10)
    at /packages/minimap-plus/lib/minimap-element.js:780:12
```

### Commands

```
     -0:21.9.0 datatip:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-base 1.4.1 
atom-ide-datatip 0.15.0 
atom-ide-definitions 0.4.0 
atom-ide-hyperclick 1.0.4 
atom-ide-javascript 1.2.1 
atom-ide-markdown-service 1.3.3 
atom-ide-outline 1.11.0 
atom-ide-signature-help 0.9.0 
atom-typescript 14.0.2 
autocomplete-paths 2.12.2 
busy-signal 2.0.1 
ide-css 0.3.5 
ide-html 0.6.2 
ide-python 1.5.0 
intentions 1.1.5 
javascript-drag-import 0.1.13 
linter 3.1.1 
linter-eslint 8.5.5 
linter-ui-default 2.1.2 
minimap 4.29.9 
minimap-linter 2.2.1 
minimap-plus 4.32.0 
teletype 0.13.4 
```

**Comment by paul-grassl** [comment]
I experience the same. There is a pull request that seems to tackle the problem but I guess it didn't pass all checks yet...?
